update packages
Developer-DAO/create-dao pull request #39
Opened 2022-01-13 20:31 UTC by e-roy

update packages to reflect dev for the end user and fixed errors on mint page

2022-01-16 21:13 UTC, Dhaiwat10 requested changes
Couple of changes and we're good to go!

2022-01-16 21:13 UTC, Dhaiwat10 commented on packages/create-dao/templates/default/pages/mint.js
>    const nftContract = useContract(NFTContractAddress, NFT_ABI.abi);
```suggestion
  const [nftContract, isReady] = useContract(NFTContractAddress, NFT_ABI.abi);
```

2022-01-16 21:13 UTC, Dhaiwat10 commented on packages/create-dao/templates/default/pages/mint.js
> +      await nftContract[0].cost(),
You can just revert these changes then

2022-01-17 01:03 UTC, e-roy commented
updated web3-ui package to 0.5.1 and tested

2022-01-17 01:28 UTC, Dhaiwat10 approved these changes

2022-01-17 01:28 UTC, merged